export const CompaniesQ = [
    {
        id: 'name',
        label: 'Nombre de la empresa:',
        type: 'text',
        placeholder: 'Nombre',
        size: 35,
        value: '',
        icon: 'name.svg',
    },
    {
        id: 'line',
        label: 'Giro de la empresa:',
        type: 'text',
        placeholder: 'Giro',
        size: 35,
        value: '',
        icon: 'services.svg',
    },
    {
        id: 'mision',
        label: 'Misión de la empresa:',
        type: 'textarea',
        placeholder: 'Misión',
        rows: 3,
        value: '',
    },
    {
        id: 'vision',
        label: 'Visión de la empresa:',
        type: 'textarea',
        placeholder: 'Visión',
        rows: 3,
        value: '',
    },
]

export const UsersQ = [
    {
        id: 'fullname',
        label: 'Nombre completo:',
        type: 'text',
        placeholder: 'Nombre',
        size: 35,
        value: '',
        icon: 'person.svg',
    },
    {
        id: 'position',
        label: 'Puesto de trabajo:',
        type: 'text',
        placeholder: 'Puesto',
        size: 35,
        value: '',
        icon: 'seniority.svg',
    },
    {
        id: 'area',
        label: 'Departamento:',
        type: 'text',
        placeholder: 'Departamento',
        size: 35,
        value: '',
        icon: 'position.svg',
    },
    {
        id: 'mail',
        label: 'Email:',
        type: 'text',
        placeholder: 'Email',
        size: 35,
        value: '',
        icon: 'mail.svg',
    },
]